services:
    postgresql:
        image: postgres:14.4-alpine
        env_file:
            - .env
        volumes:
            - gewisdb_postgresql:/var/lib/postgresql/data:rw
            - ./docker/pgadmin/create-gewisdb_report-database.sh:/docker-entrypoint-initdb.d/create-database.sh
        networks:
            - gewisdb_network
        ports:
            - "5432:5432"
        restart: unless-stopped
    pgadmin:
        image: dpage/pgadmin4:latest
        build:
            dockerfile: docker/pgadmin/Dockerfile
            context: .
        env_file:
            - .env
        depends_on:
            - postgresql
        networks:
            - gewisdb_network
        ports:
            - "8080:80"
        restart: unless-stopped
    postfix:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
    nginx:
        build: docker/nginx
        ports:
            - "80:9725"
    stripe:
        image: stripe/stripe-cli:latest
        command: listen --forward-to nginx:9725/member/subscribe/checkout/webhook
        environment:
            - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
            - STRIPE_DEVICE_NAME="GEWISDB on ${HOST:-}${NAME:-}"
            - STRIPE_CLI_TELEMETRY_OPTOUT=1
        depends_on:
            - nginx
        networks:
            - gewisdb_network
    web:
        image: abc-db.docker-registry.gewis.nl/gewisdb_web:development
        build:
            dockerfile: docker/web/development/Dockerfile
            context: .
        depends_on:
            - postgresql

volumes:
    gewisdb_postgresql:
